name: batch export
on: 
 workflow_dispatch:
   inputs:
     start:
       description: 'Start Date'     
       required: true
       default: 'YYYY-MM-DD'
     end:
       description: 'End Date'     
       required: true
       default: 'YYYY-MM-DD'

env:
  TZ: 'Asia/Tokyo'
  TW_UNAME: 'Ekusuwada' 
  HT_ID: 'kusuwada'
  HT_ROOT: 'kusuwada.hatenadiary.com'

jobs:
  batch:
    name: Batch Export
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Export
        run: |
          export TW_API_KEY=${{ secrets.TW_API_KEY }}
          export TW_API_KEY_SECRET=${{ secrets.TW_API_KEY_SECRET }}
          export TW_CLIENT_ID=${{ secrets.TW_CLIENT_ID }}
          export TW_CLIENT_SECRET=${{ secrets.TW_CLIENT_SECRET }}
          export HT_KEY=${{ secrets.HT_KEY }} 
          pip install -r requirements.txt
          python batch.py ${{ github.event.inputs.start }} ${{ github.event.inputs.end }} $TW_UNAME $HT_ID $HT_ROOT ${{ runner.temp }} --tz=$TZ
