name: daily export
on:
  schedule:
    - cron: '0 2 * * *'

env:
  TZ: 'Asia/Tokyo'
  TW_UNAME: 'Ekusuwada' 
  HT_ID: 'kusuwada'
  HT_ROOT: 'kusuwada.hatenadiary.com'

jobs:
  daily:
    name: Daily Export
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        run: echo "DATE=$(date --date '1 day ago' +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Chekout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Main
        run: |
          export TW_API_KEY=${{ secrets.TW_API_KEY }}
          export TW_API_KEY_SECRET=${{ secrets.TW_API_KEY_SECRET }}
          export TW_CLIENT_ID=${{ secrets.TW_CLIENT_ID }}
          export TW_CLIENT_SECRET=${{ secrets.TW_CLIENT_SECRET }}
          export HT_KEY=${{ secrets.HT_KEY }}          
          pip install -r requirements.txt
          python daily.py $DATE $TW_UNAME $HT_ID $HT_ROOT ${{ runner.temp }} --tz=$TZ
